import React, { useState, useRef } from 'react';
import { 
  X, 
  UserPlus, 
  Users, 
  Building2, 
  Plus, 
  Trash2, 
  DollarSign, 
  Banknote, 
  Landmark, 
  Smartphone, 
  FileText, 
  ClipboardPaste, 
  Sparkles, 
  Check, 
  AlertCircle, 
  Layers, 
  ArrowRight, 
  Phone, 
  Cake, 
  Calendar, 
  Mail,
  Upload,
  Camera
} from 'lucide-react';
import { EmployeeProfile, CompanySettings, SalaryStructureType, PaymentMethod } from '../types/payroll';

interface AddEmployeeModalProps {
  isOpen: boolean;
  onClose: () => void;
  onAddEmployee: (employee: EmployeeProfile) => void;
  onAddMultipleEmployees?: (employees: EmployeeProfile[]) => void;
  settings: CompanySettings;
  existingCount: number;
}

interface BulkRowItem {
  id: string;
  empId: string;
  name: string;
  mobileNumber?: string;
  email: string;
  dob?: string;
  department: string;
  designation: string;
  structureType: SalaryStructureType;
  baseSalary: number;
  hourlyRate: number;
  preferredPaymentMethod: PaymentMethod;
  bankName: string;
  accountNumber: string;
  routingOrIfsc: string;
  pfAccountNumber?: string;
  joinDate: string;
}

const DEPARTMENTS = [
  'XML',
  'ePub',
  'PPT',
  'Word',
];

export const AddEmployeeModal: React.FC<AddEmployeeModalProps> = ({
  isOpen,
  onClose,
  onAddEmployee,
  onAddMultipleEmployees,
  settings,
  existingCount,
}) => {
  const todayDateStr = new Date().toISOString().split('T')[0];
  const sym = settings.currencySymbol || '$';
  const autoGeneratedId = `EMP-${(1000 + existingCount + 1).toString()}`;

  // Mode: 'single' or 'bulk'
  const [activeTab, setActiveTab] = useState<'single' | 'bulk'>('single');

  // Single Form State
  const [formData, setFormData] = useState<Partial<EmployeeProfile>>({
    empId: autoGeneratedId,
    name: '',
    mobileNumber: '',
    email: '',
    dob: '',
    department: 'XML',
    designation: '',
    joinDate: todayDateStr,
    structureType: 'fixed',
    baseSalary: 15000,
    hourlyRate: 35,
    preferredPaymentMethod: 'bank_transfer',
    bankName: 'Corporate Bank',
    accountNumber: '',
    routingOrIfsc: '',
    pfAccountNumber: '',
  });
  const [errors, setErrors] = useState<Record<string, string>>({});

  // Bulk Multi-Row State
  const generateInitialBulkRows = (): BulkRowItem[] => {
    return Array.from({ length: 3 }).map((_, idx) => ({
      id: `bulk-row-${Date.now()}-${idx}`,
      empId: `EMP-${(1000 + existingCount + idx + 1).toString()}`,
      name: '',
      mobileNumber: '',
      email: '',
      dob: '',
      department: 'XML',
      designation: '',
      structureType: 'fixed',
      baseSalary: 15000,
      hourlyRate: 30,
      preferredPaymentMethod: 'bank_transfer',
      bankName: 'Corporate Bank',
      accountNumber: '',
      routingOrIfsc: '',
      pfAccountNumber: '',
      joinDate: todayDateStr,
    }));
  };

  const [bulkRows, setBulkRows] = useState<BulkRowItem[]>(generateInitialBulkRows);
  const [bulkError, setBulkError] = useState<string | null>(null);
  const [showPasteDrawer, setShowPasteDrawer] = useState(false);
  const [pasteText, setPasteText] = useState('');
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [photoError, setPhotoError] = useState<string>('');

  if (!isOpen) return null;

  const handlePhotoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    setPhotoError('');
    if (!file) return;

    const validTypes = ['image/jpeg', 'image/jpg', 'image/png'];
    const validExtensions = ['.jpg', '.jpeg', '.png'];
    const hasValidExt = validExtensions.some(ext => file.name.toLowerCase().endsWith(ext));

    if (!validTypes.includes(file.type) && !hasValidExt) {
      setPhotoError('Invalid image format. Please select a JPG or PNG file.');
      return;
    }

    if (file.size > 3 * 1024 * 1024) {
      setPhotoError('Image size exceeds 3MB. Please upload a smaller photo.');
      return;
    }

    const reader = new FileReader();
    reader.onload = () => {
      if (typeof reader.result === 'string') {
        setFormData(prev => ({ ...prev, avatarUrl: reader.result as string }));
      }
    };
    reader.readAsDataURL(file);
  };

  const handleRemovePhoto = () => {
    setFormData(prev => ({ ...prev, avatarUrl: undefined }));
    setPhotoError('');
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  // Single Form Validation & Submit
  const validateSingle = () => {
    const errs: Record<string, string> = {};
    if (!formData.name?.trim()) errs.name = 'Full name is required';
    if (!formData.empId?.trim()) errs.empId = 'Employee ID is required';
    if (!formData.designation?.trim()) errs.designation = 'Designation is required';
    if (!formData.baseSalary || formData.baseSalary <= 0) errs.baseSalary = 'Valid base salary is required';
    setErrors(errs);
    return Object.keys(errs).length === 0;
  };

  const handleSingleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!validateSingle()) return;

    const newEmployee: EmployeeProfile = {
      id: `emp-${Date.now()}`,
      empId: formData.empId || autoGeneratedId,
      name: formData.name || 'New Employee',
      mobileNumber: formData.mobileNumber?.trim() || '',
      email: formData.email || `${formData.name?.toLowerCase().replace(/\s+/g, '.')}@${(settings.name || 'company').toLowerCase().replace(/\s+/g, '')}.com`,
      dob: formData.dob?.trim() || '',
      department: formData.department || 'XML',
      designation: formData.designation || 'Specialist',
      joinDate: formData.joinDate?.trim() || todayDateStr,
      structureType: (formData.structureType as SalaryStructureType) || 'fixed',
      baseSalary: Number(formData.baseSalary) || 5000,
      hourlyRate: Number(formData.hourlyRate) || 35,
      preferredPaymentMethod: (formData.preferredPaymentMethod as PaymentMethod) || 'bank_transfer',
      bankName: formData.bankName || (formData.preferredPaymentMethod === 'cash' ? 'Cash Handover / Treasury' : 'Corporate Bank'),
      accountNumber: formData.accountNumber || (formData.preferredPaymentMethod === 'cash' ? 'CASH-DISBURSAL' : '1029384756'),
      routingOrIfsc: formData.routingOrIfsc || (formData.preferredPaymentMethod === 'cash' ? 'CASH' : 'CORP001'),
      panOrTaxNumber: '',
      pfAccountNumber: formData.pfAccountNumber?.trim() || '',
    };

    if (onAddMultipleEmployees) {
      onAddMultipleEmployees([newEmployee]);
    } else {
      onAddEmployee(newEmployee);
    }
    onClose();
  };

  // Bulk Multi-Row Handlers
  const handleAddBulkRow = () => {
    const nextIndex = existingCount + bulkRows.length + 1;
    const newRow: BulkRowItem = {
      id: `bulk-row-${Date.now()}-${Math.random()}`,
      empId: `EMP-${(1000 + nextIndex).toString()}`,
      name: '',
      mobileNumber: '',
      email: '',
      dob: '',
      department: bulkRows.length > 0 ? bulkRows[bulkRows.length - 1].department : 'XML',
      designation: '',
      structureType: 'fixed',
      baseSalary: bulkRows.length > 0 ? bulkRows[bulkRows.length - 1].baseSalary : 15000,
      hourlyRate: 30,
      preferredPaymentMethod: bulkRows.length > 0 ? bulkRows[bulkRows.length - 1].preferredPaymentMethod : 'bank_transfer',
      bankName: 'Corporate Bank',
      accountNumber: '',
      routingOrIfsc: '',
      pfAccountNumber: '',
      joinDate: todayDateStr,
    };
    setBulkRows(prev => [...prev, newRow]);
  };

  const handleAddMultipleBlankRows = (count: number) => {
    const newItems: BulkRowItem[] = Array.from({ length: count }).map((_, idx) => {
      const nextIndex = existingCount + bulkRows.length + idx + 1;
      return {
        id: `bulk-row-${Date.now()}-${idx}-${Math.random()}`,
        empId: `EMP-${(1000 + nextIndex).toString()}`,
        name: '',
        mobileNumber: '',
        email: '',
        dob: '',
        department: 'XML',
        designation: '',
        structureType: 'fixed',
        baseSalary: 15000,
        hourlyRate: 30,
        preferredPaymentMethod: 'bank_transfer',
        bankName: 'Corporate Bank',
        accountNumber: '',
        routingOrIfsc: '',
        pfAccountNumber: '',
        joinDate: todayDateStr,
      };
    });
    setBulkRows(prev => [...prev, ...newItems]);
  };

  const handleRemoveBulkRow = (id: string) => {
    if (bulkRows.length <= 1) {
      // Clear instead of removing last row
      setBulkRows([{
        ...bulkRows[0],
        name: '',
        designation: '',
      }]);
      return;
    }
    setBulkRows(prev => prev.filter(r => r.id !== id));
  };

  const updateBulkRow = (id: string, field: keyof BulkRowItem, value: any) => {
    setBulkRows(prev => prev.map(r => r.id === id ? { ...r, [field]: value } : r));
    if (bulkError) setBulkError(null);
  };

  // Fast Batch Fill Helpers
  const handleBatchSetDepartment = (dept: string) => {
    setBulkRows(prev => prev.map(r => ({ ...r, department: dept })));
  };

  const handleBatchSetPaymentMethod = (method: PaymentMethod) => {
    setBulkRows(prev => prev.map(r => ({ ...r, preferredPaymentMethod: method })));
  };

  const handleBatchSetJoinDate = (date: string) => {
    if (!date) return;
    setBulkRows(prev => prev.map(r => ({ ...r, joinDate: date })));
  };

  // Quick Parse from Pasted Tab-Separated (Excel / Google Sheets) or Comma-Separated Data
  const handleParsePastedData = () => {
    if (!pasteText.trim()) return;

    const lines = pasteText.trim().split('\n');
    const parsedRows: BulkRowItem[] = [];

    lines.forEach((line, index) => {
      // Split by tab or comma
      const cols = line.includes('\t') ? line.split('\t') : line.split(',');
      if (cols.length === 0 || !cols[0].trim()) return;

      // Skip header row if it contains 'name' or 'employee'
      if (index === 0 && (cols[0].toLowerCase().includes('name') || cols[0].toLowerCase().includes('emp'))) {
        return;
      }

      const name = cols[0]?.trim() || `Employee ${index + 1}`;
      
      // Check if second column looks like an email or department
      let email = '';
      let department = 'XML';
      let designation = 'Specialist';
      let salary = 15000;
      let paymentStr = 'bank_transfer';
      let parsedJoinDate = todayDateStr;

      if (cols[1]?.includes('@')) {
        email = cols[1].trim();
        department = cols[2]?.trim() || 'XML';
        designation = cols[3]?.trim() || 'Specialist';
        salary = parseFloat(cols[4]?.replace(/[^0-9.]/g, '') || '') || 15000;
        paymentStr = cols[5]?.toLowerCase().trim() || 'bank_transfer';
        parsedJoinDate = cols[6]?.trim() && cols[6].trim().match(/^\d{4}-\d{2}-\d{2}$/) ? cols[6].trim() : todayDateStr;
      } else {
        department = cols[1]?.trim() || 'XML';
        designation = cols[2]?.trim() || 'Specialist';
        salary = parseFloat(cols[3]?.replace(/[^0-9.]/g, '') || '') || 15000;
        paymentStr = cols[4]?.toLowerCase().trim() || 'bank_transfer';
        parsedJoinDate = cols[5]?.trim() && cols[5].trim().match(/^\d{4}-\d{2}-\d{2}$/) ? cols[5].trim() : todayDateStr;
        email = `${name.toLowerCase().replace(/\s+/g, '.')}@${(settings.name || 'company').toLowerCase().replace(/\s+/g, '')}.com`;
      }

      const paymentMethod: PaymentMethod = paymentStr.includes('cash') 
        ? 'cash' 
        : paymentStr.includes('upi') 
        ? 'upi' 
        : paymentStr.includes('cheque') 
        ? 'cheque' 
        : 'bank_transfer';

      const nextIdNum = existingCount + parsedRows.length + 1;

      parsedRows.push({
        id: `bulk-pasted-${Date.now()}-${index}`,
        empId: `EMP-${(1000 + nextIdNum).toString()}`,
        name,
        mobileNumber: '',
        email,
        dob: '',
        department: DEPARTMENTS.includes(department) ? department : 'XML',
        designation,
        structureType: 'fixed',
        baseSalary: salary,
        hourlyRate: 30,
        preferredPaymentMethod: paymentMethod,
        bankName: 'Corporate Bank',
        accountNumber: '',
        routingOrIfsc: '',
        pfAccountNumber: '',
        joinDate: parsedJoinDate,
      });
    });

    if (parsedRows.length > 0) {
      setBulkRows(parsedRows);
      setShowPasteDrawer(false);
      setPasteText('');
      setBulkError(null);
    } else {
      setBulkError('Could not find valid rows to parse. Please check your text format.');
    }
  };

  // Bulk Submit Handler
  const handleBulkSubmit = () => {
    // Filter rows that have at least a name
    const validRows = bulkRows.filter(r => r.name.trim().length > 0);

    if (validRows.length === 0) {
      setBulkError('Please enter full name for at least one employee before submitting.');
      return;
    }

    // Check if any valid row is missing designation or has invalid salary
    for (let i = 0; i < validRows.length; i++) {
      const r = validRows[i];
      if (!r.designation.trim()) {
        setBulkError(`Please provide a Designation for row #${i + 1} (${r.name}).`);
        return;
      }
      if (!r.baseSalary || r.baseSalary <= 0) {
        setBulkError(`Please provide a valid Base Salary for row #${i + 1} (${r.name}).`);
        return;
      }
    }

    const newEmployees: EmployeeProfile[] = validRows.map((r, idx) => ({
      id: `emp-${Date.now()}-${idx}`,
      empId: r.empId || `EMP-${(1000 + existingCount + idx + 1).toString()}`,
      name: r.name.trim(),
      mobileNumber: r.mobileNumber?.trim() || '',
      email: r.email || `${r.name.toLowerCase().replace(/\s+/g, '.')}@${(settings.name || 'company').toLowerCase().replace(/\s+/g, '')}.com`,
      dob: r.dob?.trim() || '',
      department: r.department || 'General',
      designation: r.designation.trim(),
      joinDate: r.joinDate?.trim() || todayDateStr,
      structureType: r.structureType || 'fixed',
      baseSalary: Number(r.baseSalary) || 4500,
      hourlyRate: Number(r.hourlyRate) || 30,
      preferredPaymentMethod: r.preferredPaymentMethod || 'bank_transfer',
      bankName: r.bankName || (r.preferredPaymentMethod === 'cash' ? 'Cash Handover / Treasury' : 'Corporate Bank'),
      accountNumber: r.accountNumber || (r.preferredPaymentMethod === 'cash' ? 'CASH-DISBURSAL' : `ACC-9028${idx}`),
      routingOrIfsc: r.routingOrIfsc || (r.preferredPaymentMethod === 'cash' ? 'CASH' : 'CORP001'),
      panOrTaxNumber: '',
      pfAccountNumber: r.pfAccountNumber?.trim() || '',
    }));

    if (onAddMultipleEmployees) {
      onAddMultipleEmployees(newEmployees);
    } else {
      newEmployees.forEach(emp => onAddEmployee(emp));
    }

    onClose();
  };

  const validRowCount = bulkRows.filter(r => r.name.trim().length > 0).length;

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-900/70 backdrop-blur-xs flex items-center justify-center p-4">
      <div className={`bg-white rounded-2xl shadow-2xl border border-slate-200 w-full overflow-hidden transition-all duration-200 ${
        activeTab === 'bulk' ? 'max-w-5xl' : 'max-w-2xl'
      }`}>
        
        {/* Modal Header */}
        <div className="px-6 py-4 border-b border-slate-200 flex items-center justify-between bg-slate-50">
          <div className="flex items-center space-x-2.5">
            <div className="w-8 h-8 rounded-lg bg-blue-600 text-white flex items-center justify-center font-bold">
              {activeTab === 'bulk' ? <Users className="w-4 h-4" /> : <UserPlus className="w-4 h-4" />}
            </div>
            <div>
              <h2 className="text-sm font-bold text-slate-900">
                {activeTab === 'bulk' ? 'Bulk Onboard Multiple Employees' : 'Add Single Employee to Payroll'}
              </h2>
              <p className="text-xs text-slate-500">
                {activeTab === 'bulk' 
                  ? 'Add 2, 5, 10, or more employees simultaneously with compensation & payment modes'
                  : 'Configure single employee salary structure, compensation & banking credentials'
                }
              </p>
            </div>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-600 p-1.5 rounded-lg cursor-pointer">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Selector: Single vs Multiple Employees */}
        <div className="px-6 border-b border-slate-200 flex items-center justify-between bg-white text-xs font-semibold">
          <div className="flex space-x-4">
            <button
              id="tab-single-employee"
              onClick={() => setActiveTab('single')}
              className={`py-3 border-b-2 flex items-center space-x-1.5 transition cursor-pointer ${
                activeTab === 'single'
                  ? 'border-blue-600 text-blue-600'
                  : 'border-transparent text-slate-500 hover:text-slate-800'
              }`}
            >
              <UserPlus className="w-3.5 h-3.5" />
              <span>Single Employee Form</span>
            </button>

            <button
              id="tab-bulk-employee"
              onClick={() => setActiveTab('bulk')}
              className={`py-3 border-b-2 flex items-center space-x-1.5 transition cursor-pointer ${
                activeTab === 'bulk'
                  ? 'border-blue-600 text-blue-600'
                  : 'border-transparent text-slate-500 hover:text-slate-800'
              }`}
            >
              <Users className="w-3.5 h-3.5" />
              <span>Add Multiple Employees (1 Step)</span>
              <span className="text-[10px] bg-blue-100 text-blue-700 font-bold px-1.5 py-0.2 rounded-full">
                Multi-Row
              </span>
            </button>
          </div>

          {activeTab === 'bulk' && (
            <div className="flex items-center space-x-2 py-2">
              <button
                type="button"
                onClick={() => setShowPasteDrawer(!showPasteDrawer)}
                className="px-2.5 py-1 rounded-lg border border-slate-300 hover:bg-slate-50 text-slate-700 text-[11px] font-medium flex items-center space-x-1 cursor-pointer"
                title="Paste tabular rows copied from Excel or Google Sheets"
              >
                <ClipboardPaste className="w-3.5 h-3.5 text-indigo-600" />
                <span>Paste from Excel / Sheets</span>
              </button>
            </div>
          )}
        </div>

        {/* ----------------- TAB 1: SINGLE EMPLOYEE ----------------- */}
        {activeTab === 'single' && (
          <form onSubmit={handleSingleSubmit} className="p-6 max-h-[72vh] overflow-y-auto space-y-4 text-xs">
            
            {/* Profile Picture Upload */}
            <div className="p-3.5 bg-slate-50 border border-slate-200 rounded-xl flex flex-col sm:flex-row items-center gap-4">
              <div className="w-14 h-14 rounded-full bg-white border-2 border-slate-300 shadow-2xs flex items-center justify-center font-bold text-base text-slate-700 overflow-hidden shrink-0">
                {formData.avatarUrl ? (
                  <img src={formData.avatarUrl} alt={formData.name || 'New Employee'} className="w-full h-full object-cover" />
                ) : (
                  <span className="text-slate-400 font-bold">{formData.name ? formData.name.charAt(0).toUpperCase() : <Camera className="w-5 h-5 text-slate-400" />}</span>
                )}
              </div>

              <div className="flex-1 text-center sm:text-left space-y-1">
                <div className="font-bold text-slate-800 text-xs flex items-center justify-center sm:justify-start space-x-1.5">
                  <Camera className="w-3.5 h-3.5 text-blue-600" />
                  <span>Profile Photo</span>
                  <span className="text-[10px] font-semibold text-slate-500">(JPG, PNG)</span>
                </div>
                <p className="text-[11px] text-slate-500">
                  Upload employee headshot in JPG or PNG format (maximum 3MB).
                </p>
                {photoError && (
                  <p className="text-[11px] text-rose-500 font-medium">{photoError}</p>
                )}
              </div>

              <div className="flex items-center space-x-2 shrink-0">
                <input
                  type="file"
                  ref={fileInputRef}
                  onChange={handlePhotoUpload}
                  accept=".jpg,.jpeg,.png,image/jpeg,image/png"
                  className="hidden"
                />
                <button
                  type="button"
                  onClick={() => fileInputRef.current?.click()}
                  className="inline-flex items-center space-x-1.5 px-3 py-1.5 rounded-lg bg-blue-50 hover:bg-blue-100 text-blue-700 border border-blue-200 font-bold text-xs transition cursor-pointer shadow-2xs"
                >
                  <Upload className="w-3.5 h-3.5" />
                  <span>{formData.avatarUrl ? 'Change Photo' : 'Upload Photo'}</span>
                </button>

                {formData.avatarUrl && (
                  <button
                    type="button"
                    onClick={handleRemovePhoto}
                    className="p-1.5 rounded-lg bg-rose-50 hover:bg-rose-100 text-rose-600 border border-rose-200 transition cursor-pointer"
                    title="Remove Profile Photo"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                )}
              </div>
            </div>

            {/* Personal & Organization Details */}
            <div>
              <h3 className="font-bold text-slate-900 text-xs mb-2.5 flex items-center space-x-1.5">
                <Building2 className="w-3.5 h-3.5 text-blue-600" />
                <span>Employee Information</span>
              </h3>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="font-semibold text-slate-700 block mb-1">
                    Employee ID <span className="text-rose-500">*</span>
                  </label>
                  <input
                    type="text"
                    value={formData.empId}
                    onChange={(e) => setFormData({ ...formData, empId: e.target.value })}
                    placeholder="e.g. EMP-1008"
                    className={`w-full font-medium bg-slate-50 border rounded-lg p-2 focus:bg-white focus:outline-none focus:ring-1 ${
                      errors.empId ? 'border-rose-400 focus:ring-rose-500' : 'border-slate-300 focus:ring-blue-500'
                    }`}
                  />
                  {errors.empId && <p className="text-[10px] text-rose-500 mt-0.5">{errors.empId}</p>}
                </div>

                <div>
                  <label className="font-semibold text-slate-700 block mb-1">
                    Full Name <span className="text-rose-500">*</span>
                  </label>
                  <input
                    type="text"
                    value={formData.name}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                    placeholder="e.g. Jessica Taylor"
                    className={`w-full font-medium bg-slate-50 border rounded-lg p-2 focus:bg-white focus:outline-none focus:ring-1 ${
                      errors.name ? 'border-rose-400 focus:ring-rose-500' : 'border-slate-300 focus:ring-blue-500'
                    }`}
                  />
                  {errors.name && <p className="text-[10px] text-rose-500 mt-0.5">{errors.name}</p>}
                </div>

                <div>
                  <label className="font-semibold text-slate-700 block mb-1 flex items-center space-x-1">
                    <Phone className="w-3.5 h-3.5 text-emerald-600" />
                    <span>Mobile Number</span>
                  </label>
                  <input
                    type="tel"
                    value={formData.mobileNumber || ''}
                    onChange={(e) => setFormData({ ...formData, mobileNumber: e.target.value })}
                    placeholder="e.g. +91 98401 23456"
                    className="w-full font-medium bg-slate-50 border border-slate-300 rounded-lg p-2 focus:bg-white focus:outline-none focus:ring-1 focus:ring-blue-500"
                  />
                </div>

                <div>
                  <label className="font-semibold text-slate-700 block mb-1 flex items-center space-x-1">
                    <Mail className="w-3.5 h-3.5 text-blue-600" />
                    <span>Work Email</span>
                  </label>
                  <input
                    type="email"
                    value={formData.email}
                    onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                    placeholder="jessica.taylor@company.com"
                    className="w-full font-medium bg-slate-50 border border-slate-300 rounded-lg p-2 focus:bg-white focus:outline-none focus:ring-1 focus:ring-blue-500"
                  />
                </div>

                <div>
                  <label className="font-semibold text-slate-700 block mb-1 flex items-center space-x-1">
                    <Cake className="w-3.5 h-3.5 text-rose-500" />
                    <span>Date of Birth (DOB)</span>
                  </label>
                  <input
                    type="date"
                    value={formData.dob || ''}
                    onChange={(e) => setFormData({ ...formData, dob: e.target.value })}
                    className="w-full font-medium bg-slate-50 border border-slate-300 rounded-lg p-2 focus:bg-white focus:outline-none focus:ring-1 focus:ring-blue-500"
                  />
                </div>

                <div>
                  <label className="font-semibold text-slate-700 block mb-1">Department</label>
                  <select
                    value={formData.department}
                    onChange={(e) => setFormData({ ...formData, department: e.target.value })}
                    className="w-full font-medium bg-slate-50 border border-slate-300 rounded-lg p-2 focus:bg-white focus:outline-none focus:ring-1 focus:ring-blue-500"
                  >
                    {DEPARTMENTS.map(dept => (
                      <option key={dept} value={dept}>{dept}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="font-semibold text-slate-700 block mb-1">
                    Designation / Role <span className="text-rose-500">*</span>
                  </label>
                  <input
                    type="text"
                    value={formData.designation}
                    onChange={(e) => setFormData({ ...formData, designation: e.target.value })}
                    placeholder="e.g. Senior XML Specialist"
                    className={`w-full font-medium bg-slate-50 border rounded-lg p-2 focus:bg-white focus:outline-none focus:ring-1 ${
                      errors.designation ? 'border-rose-400 focus:ring-rose-500' : 'border-slate-300 focus:ring-blue-500'
                    }`}
                  />
                  {errors.designation && <p className="text-[10px] text-rose-500 mt-0.5">{errors.designation}</p>}
                </div>

                <div>
                  <label className="font-semibold text-slate-700 block mb-1 flex items-center space-x-1">
                    <Calendar className="w-3.5 h-3.5 text-blue-600" />
                    <span>Joining Date</span>
                  </label>
                  <input
                    type="date"
                    value={formData.joinDate}
                    onChange={(e) => setFormData({ ...formData, joinDate: e.target.value })}
                    className="w-full font-medium bg-slate-50 border border-slate-300 rounded-lg p-2 focus:bg-white focus:outline-none focus:ring-1 focus:ring-blue-500"
                  />
                </div>
              </div>
            </div>

            {/* Salary Structure & Compensation */}
            <div className="pt-2 border-t border-slate-200">
              <h3 className="font-bold text-slate-900 text-xs mb-2.5 flex items-center space-x-1.5">
                <DollarSign className="w-3.5 h-3.5 text-emerald-600" />
                <span>Salary Structure & Compensation</span>
              </h3>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="font-semibold text-slate-700 block mb-1">Structure Type</label>
                  <select
                    value={formData.structureType}
                    onChange={(e) => setFormData({ ...formData, structureType: e.target.value as SalaryStructureType })}
                    className="w-full font-medium bg-slate-50 border border-slate-300 rounded-lg p-2 focus:bg-white focus:outline-none focus:ring-1 focus:ring-blue-500"
                  >
                    <option value="fixed">Fixed Monthly Salary</option>
                    <option value="hourly">Hourly Contract</option>
                    <option value="contract">Fixed Retainer / Contractor</option>
                    <option value="piece_rate">Piece-Rate Output</option>
                  </select>
                </div>

                <div>
                  <label className="font-semibold text-slate-700 block mb-1">
                    Monthly Base Salary ({sym}) <span className="text-rose-500">*</span>
                  </label>
                  <input
                    type="number"
                    min="0"
                    step="any"
                    value={formData.baseSalary === 0 ? '' : formData.baseSalary}
                    onChange={(e) => {
                      const val = e.target.value === '' ? 0 : parseFloat(e.target.value);
                      setFormData({ ...formData, baseSalary: isNaN(val) ? 0 : val });
                    }}
                    placeholder="e.g. 15000"
                    className={`w-full font-bold bg-slate-50 border rounded-lg p-2 focus:bg-white focus:outline-none focus:ring-1 ${
                      errors.baseSalary ? 'border-rose-400 focus:ring-rose-500' : 'border-slate-300 focus:ring-blue-500'
                    }`}
                  />
                  {errors.baseSalary && <p className="text-[10px] text-rose-500 mt-0.5">{errors.baseSalary}</p>}
                </div>
              </div>
            </div>

            {/* Payment Method & Disbursal Mode */}
            <div className="pt-2 border-t border-slate-200">
              <h3 className="font-bold text-slate-900 text-xs mb-2.5 flex items-center space-x-1.5">
                <Banknote className="w-3.5 h-3.5 text-emerald-600" />
                <span>Disbursal & Payment Mode</span>
              </h3>

              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mb-3">
                <button
                  type="button"
                  onClick={() => setFormData({ ...formData, preferredPaymentMethod: 'bank_transfer' })}
                  className={`p-2.5 rounded-lg border text-left flex flex-col justify-between transition cursor-pointer ${
                    formData.preferredPaymentMethod === 'bank_transfer'
                      ? 'border-blue-600 bg-blue-50/70 text-blue-900 ring-1 ring-blue-600'
                      : 'border-slate-200 bg-slate-50 hover:bg-slate-100 text-slate-700'
                  }`}
                >
                  <Landmark className="w-4 h-4 text-blue-600 mb-1" />
                  <div>
                    <div className="font-bold text-xs">Bank Transfer</div>
                    <div className="text-[10px] text-slate-500">Direct Deposit / NEFT</div>
                  </div>
                </button>

                <button
                  type="button"
                  onClick={() => setFormData({ ...formData, preferredPaymentMethod: 'cash' })}
                  className={`p-2.5 rounded-lg border text-left flex flex-col justify-between transition cursor-pointer ${
                    formData.preferredPaymentMethod === 'cash'
                      ? 'border-emerald-600 bg-emerald-50/70 text-emerald-900 ring-1 ring-emerald-600'
                      : 'border-slate-200 bg-slate-50 hover:bg-slate-100 text-slate-700'
                  }`}
                >
                  <Banknote className="w-4 h-4 text-emerald-600 mb-1" />
                  <div>
                    <div className="font-bold text-xs">Paid by Cash</div>
                    <div className="text-[10px] text-slate-500">Physical Cash Handover</div>
                  </div>
                </button>

                <button
                  type="button"
                  onClick={() => setFormData({ ...formData, preferredPaymentMethod: 'upi' })}
                  className={`p-2.5 rounded-lg border text-left flex flex-col justify-between transition cursor-pointer ${
                    formData.preferredPaymentMethod === 'upi'
                      ? 'border-purple-600 bg-purple-50/70 text-purple-900 ring-1 ring-purple-600'
                      : 'border-slate-200 bg-slate-50 hover:bg-slate-100 text-slate-700'
                  }`}
                >
                  <Smartphone className="w-4 h-4 text-purple-600 mb-1" />
                  <div>
                    <div className="font-bold text-xs">UPI / Mobile</div>
                    <div className="text-[10px] text-slate-500">Instant Digital Pay</div>
                  </div>
                </button>

                <button
                  type="button"
                  onClick={() => setFormData({ ...formData, preferredPaymentMethod: 'cheque' })}
                  className={`p-2.5 rounded-lg border text-left flex flex-col justify-between transition cursor-pointer ${
                    formData.preferredPaymentMethod === 'cheque'
                      ? 'border-amber-600 bg-amber-50/70 text-amber-900 ring-1 ring-amber-600'
                      : 'border-slate-200 bg-slate-50 hover:bg-slate-100 text-slate-700'
                  }`}
                >
                  <FileText className="w-4 h-4 text-amber-600 mb-1" />
                  <div>
                    <div className="font-bold text-xs">Cheque</div>
                    <div className="text-[10px] text-slate-500">Paper Cheque Voucher</div>
                  </div>
                </button>
              </div>

              {formData.preferredPaymentMethod !== 'cash' && (
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-3">
                  <div>
                    <label className="font-semibold text-slate-700 block mb-1">Bank Name</label>
                    <input
                      type="text"
                      value={formData.bankName}
                      onChange={(e) => setFormData({ ...formData, bankName: e.target.value })}
                      placeholder="e.g. JPMorgan Chase / HDFC Bank"
                      className="w-full font-medium bg-slate-50 border border-slate-300 rounded-lg p-2 focus:bg-white focus:outline-none focus:ring-1 focus:ring-blue-500"
                    />
                  </div>

                  <div>
                    <label className="font-semibold text-slate-700 block mb-1">Account Number / UPI ID</label>
                    <input
                      type="text"
                      value={formData.accountNumber}
                      onChange={(e) => setFormData({ ...formData, accountNumber: e.target.value })}
                      placeholder="e.g. 4829103948 or user@upi"
                      className="w-full font-medium bg-slate-50 border border-slate-300 rounded-lg p-2 focus:bg-white focus:outline-none focus:ring-1 focus:ring-blue-500"
                    />
                  </div>

                  <div>
                    <label className="font-semibold text-slate-700 block mb-1">IFSC / Routing Code</label>
                    <input
                      type="text"
                      value={formData.routingOrIfsc}
                      onChange={(e) => setFormData({ ...formData, routingOrIfsc: e.target.value })}
                      placeholder="e.g. HDFC0001234 or CHASUS33"
                      className="w-full font-medium bg-slate-50 border border-slate-300 rounded-lg p-2 focus:bg-white focus:outline-none focus:ring-1 focus:ring-blue-500"
                    />
                  </div>

                  <div>
                    <label className="font-semibold text-slate-700 block mb-1">PF Account Number</label>
                    <input
                      type="text"
                      value={formData.pfAccountNumber || ''}
                      onChange={(e) => setFormData({ ...formData, pfAccountNumber: e.target.value })}
                      placeholder="e.g. MH/BAN/0012345/000/0001"
                      className="w-full font-medium bg-slate-50 border border-slate-300 rounded-lg p-2 focus:bg-white focus:outline-none focus:ring-1 focus:ring-blue-500"
                    />
                  </div>
                </div>
              )}
            </div>

            {/* Footer */}
            <div className="pt-4 border-t border-slate-200 flex items-center justify-between">
              <button
                type="button"
                onClick={onClose}
                className="px-4 py-2 rounded-lg border border-slate-300 text-slate-600 hover:bg-slate-50 font-semibold cursor-pointer"
              >
                Cancel
              </button>
              <button
                type="submit"
                className="px-5 py-2 rounded-lg bg-blue-600 hover:bg-blue-700 text-white font-bold shadow-xs transition cursor-pointer"
              >
                Add Single Employee
              </button>
            </div>
          </form>
        )}

        {/* ----------------- TAB 2: BULK MULTIPLE EMPLOYEES ----------------- */}
        {activeTab === 'bulk' && (
          <div className="p-6 max-h-[75vh] overflow-y-auto space-y-4 text-xs">
            
            {/* Optional Excel Paste Drawer */}
            {showPasteDrawer && (
              <div className="p-4 bg-indigo-50/80 border border-indigo-200 rounded-xl space-y-3 animate-in fade-in duration-150">
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-2">
                    <ClipboardPaste className="w-4 h-4 text-indigo-700" />
                    <span className="font-bold text-indigo-950 text-xs">Paste Rows Directly from Excel or Google Sheets</span>
                  </div>
                  <span className="text-[10px] text-indigo-600 font-medium">Format: Name | Department | Designation | Salary | Payment Mode</span>
                </div>
                
                <textarea
                  rows={4}
                  value={pasteText}
                  onChange={(e) => setPasteText(e.target.value)}
                  placeholder={`Alex Rivera\tXML\tLead Developer\t15000\tbank_transfer\nSarah Connor\tePub\tePub Conversion Lead\t15000\tcash\nDavid Kim\tPPT\tPresentation Specialist\t15000\tupi`}
                  className="w-full text-xs font-mono bg-white border border-indigo-300 rounded-lg p-2.5 focus:outline-none focus:ring-1 focus:ring-indigo-500"
                />

                <div className="flex items-center justify-between">
                  <p className="text-[11px] text-slate-500">
                    Copy columns from your spreadsheet and paste them above. Tabs and commas are automatically parsed.
                  </p>
                  <div className="flex items-center space-x-2">
                    <button
                      type="button"
                      onClick={() => setShowPasteDrawer(false)}
                      className="px-3 py-1.5 text-xs text-slate-600 hover:bg-slate-200/60 rounded-lg cursor-pointer"
                    >
                      Cancel
                    </button>
                    <button
                      type="button"
                      onClick={handleParsePastedData}
                      className="px-3.5 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs rounded-lg shadow-2xs transition cursor-pointer flex items-center space-x-1.5"
                    >
                      <Sparkles className="w-3.5 h-3.5" />
                      <span>Parse & Populate Table</span>
                    </button>
                  </div>
                </div>
              </div>
            )}

            {/* Batch Helper Quick Bar */}
            <div className="flex flex-wrap items-center justify-between gap-2 p-3 bg-slate-50 border border-slate-200 rounded-xl">
              <div className="flex items-center space-x-2">
                <span className="font-bold text-slate-700 text-xs">Batch Controls:</span>
                <button
                  type="button"
                  onClick={handleAddBulkRow}
                  className="px-2.5 py-1 bg-white hover:bg-slate-100 border border-slate-300 rounded-lg text-slate-800 font-semibold text-[11px] transition cursor-pointer flex items-center space-x-1 shadow-2xs"
                >
                  <Plus className="w-3.5 h-3.5 text-blue-600" />
                  <span>+ Add Row</span>
                </button>

                <button
                  type="button"
                  onClick={() => handleAddMultipleBlankRows(5)}
                  className="px-2.5 py-1 bg-white hover:bg-slate-100 border border-slate-300 rounded-lg text-slate-800 font-semibold text-[11px] transition cursor-pointer flex items-center space-x-1 shadow-2xs"
                >
                  <Plus className="w-3.5 h-3.5 text-blue-600" />
                  <span>+ Add 5 Rows</span>
                </button>
              </div>

              {/* Quick Fill Dropdowns */}
              <div className="flex flex-wrap items-center gap-2 sm:gap-3 text-[11px]">
                <div className="flex items-center space-x-1">
                  <span className="text-slate-500 font-medium">Set All Depts:</span>
                  <select
                    onChange={(e) => {
                      if (e.target.value) handleBatchSetDepartment(e.target.value);
                    }}
                    defaultValue=""
                    className="bg-white border border-slate-300 rounded px-1.5 py-0.5 text-slate-800 font-medium cursor-pointer"
                  >
                    <option value="" disabled>Select...</option>
                    {DEPARTMENTS.map(d => (
                      <option key={d} value={d}>{d}</option>
                    ))}
                  </select>
                </div>

                <div className="flex items-center space-x-1">
                  <span className="text-slate-500 font-medium">Set All Modes:</span>
                  <select
                    onChange={(e) => {
                      if (e.target.value) handleBatchSetPaymentMethod(e.target.value as PaymentMethod);
                    }}
                    defaultValue=""
                    className="bg-white border border-slate-300 rounded px-1.5 py-0.5 text-slate-800 font-medium cursor-pointer"
                  >
                    <option value="" disabled>Select...</option>
                    <option value="bank_transfer">🏦 Bank Transfer</option>
                    <option value="cash">💵 Paid by Cash</option>
                    <option value="upi">📱 UPI / Mobile</option>
                    <option value="cheque">📝 Cheque</option>
                  </select>
                </div>

                <div className="flex items-center space-x-1">
                  <span className="text-slate-500 font-medium">Set All Join Dates:</span>
                  <input
                    type="date"
                    defaultValue={todayDateStr}
                    onChange={(e) => {
                      if (e.target.value) handleBatchSetJoinDate(e.target.value);
                    }}
                    className="bg-white border border-slate-300 rounded px-1.5 py-0.5 text-slate-800 font-medium cursor-pointer"
                  />
                </div>
              </div>
            </div>

            {/* Error Banner if any */}
            {bulkError && (
              <div className="p-3 bg-rose-50 border border-rose-200 rounded-lg text-rose-800 flex items-center space-x-2 text-xs">
                <AlertCircle className="w-4 h-4 text-rose-600 shrink-0" />
                <span>{bulkError}</span>
              </div>
            )}

            {/* Multi-Row Editable Table */}
            <div className="border border-slate-200 rounded-xl overflow-hidden shadow-2xs">
              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                  <thead className="bg-slate-100 text-slate-700 font-bold uppercase text-[10px] tracking-wider border-b border-slate-200">
                    <tr>
                      <th className="p-2.5 w-10 text-center">#</th>
                      <th className="p-2.5 min-w-[90px]">Emp ID</th>
                      <th className="p-2.5 min-w-[130px]">Full Name <span className="text-rose-500">*</span></th>
                      <th className="p-2.5 min-w-[110px]">Mobile No</th>
                      <th className="p-2.5 min-w-[140px]">Work Email</th>
                      <th className="p-2.5 min-w-[115px]">Date of Birth</th>
                      <th className="p-2.5 min-w-[120px]">Department</th>
                      <th className="p-2.5 min-w-[120px]">Designation <span className="text-rose-500">*</span></th>
                      <th className="p-2.5 min-w-[120px]">Joining Date</th>
                      <th className="p-2.5 min-w-[95px]">Structure</th>
                      <th className="p-2.5 min-w-[105px]">Base Salary ({sym}) <span className="text-rose-500">*</span></th>
                      <th className="p-2.5 min-w-[115px]">Payment Mode</th>
                      <th className="p-2.5 min-w-[115px]">Account / Note</th>
                      <th className="p-2.5 min-w-[115px]">PF Account No</th>
                      <th className="p-2.5 w-10 text-center">Action</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-200 bg-white">
                    {bulkRows.map((row, index) => {
                      const isRowFilled = row.name.trim().length > 0;
                      return (
                        <tr key={row.id} className={`hover:bg-slate-50/80 transition ${isRowFilled ? 'bg-blue-50/20' : ''}`}>
                          {/* Row Number */}
                          <td className="p-2 text-center text-slate-400 font-mono text-[11px]">
                            {index + 1}
                          </td>

                          {/* Emp ID */}
                          <td className="p-2">
                            <input
                              type="text"
                              value={row.empId}
                              onChange={(e) => updateBulkRow(row.id, 'empId', e.target.value)}
                              placeholder="EMP-1008"
                              className="w-full text-xs font-mono font-medium bg-slate-50 border border-slate-200 rounded px-2 py-1 focus:bg-white focus:outline-none focus:ring-1 focus:ring-blue-500"
                            />
                          </td>

                          {/* Full Name */}
                          <td className="p-2">
                            <input
                              type="text"
                              value={row.name}
                              onChange={(e) => {
                                const newName = e.target.value;
                                updateBulkRow(row.id, 'name', newName);
                                // If email was empty or matches previous auto-gen, suggest email
                                if (!row.email || row.email.endsWith(`@${(settings.name || 'company').toLowerCase().replace(/\s+/g, '')}.com`)) {
                                  const suggested = newName.trim() 
                                    ? `${newName.toLowerCase().replace(/\s+/g, '.')}@${(settings.name || 'company').toLowerCase().replace(/\s+/g, '')}.com`
                                    : '';
                                  updateBulkRow(row.id, 'email', suggested);
                                }
                              }}
                              placeholder="e.g. Sarah Jenkins"
                              className="w-full text-xs font-medium bg-white border border-slate-300 rounded px-2 py-1 focus:outline-none focus:ring-1 focus:ring-blue-500"
                            />
                          </td>

                          {/* Mobile Number */}
                          <td className="p-2">
                            <input
                              type="tel"
                              value={row.mobileNumber || ''}
                              onChange={(e) => updateBulkRow(row.id, 'mobileNumber', e.target.value)}
                              placeholder="+1 555-0199"
                              className="w-full text-xs font-medium bg-white border border-slate-300 rounded px-2 py-1 focus:outline-none focus:ring-1 focus:ring-blue-500"
                            />
                          </td>

                          {/* Work Email */}
                          <td className="p-2">
                            <input
                              type="email"
                              value={row.email}
                              onChange={(e) => updateBulkRow(row.id, 'email', e.target.value)}
                              placeholder="name@company.com"
                              className="w-full text-xs font-medium bg-slate-50 border border-slate-200 rounded px-2 py-1 focus:bg-white focus:outline-none focus:ring-1 focus:ring-blue-500"
                            />
                          </td>

                          {/* Date of Birth */}
                          <td className="p-2">
                            <input
                              type="date"
                              value={row.dob || ''}
                              onChange={(e) => updateBulkRow(row.id, 'dob', e.target.value)}
                              className="w-full text-xs font-medium bg-white border border-slate-300 rounded px-1.5 py-1 focus:outline-none focus:ring-1 focus:ring-blue-500"
                            />
                          </td>

                          {/* Department */}
                          <td className="p-2">
                            <select
                              value={row.department}
                              onChange={(e) => updateBulkRow(row.id, 'department', e.target.value)}
                              className="w-full text-xs bg-slate-50 border border-slate-300 rounded px-1.5 py-1 focus:bg-white focus:outline-none focus:ring-1 focus:ring-blue-500"
                            >
                              {DEPARTMENTS.map(d => (
                                <option key={d} value={d}>{d}</option>
                              ))}
                            </select>
                          </td>

                          {/* Designation */}
                          <td className="p-2">
                            <input
                              type="text"
                              value={row.designation}
                              onChange={(e) => updateBulkRow(row.id, 'designation', e.target.value)}
                              placeholder="e.g. Developer"
                              className="w-full text-xs bg-white border border-slate-300 rounded px-2 py-1 focus:outline-none focus:ring-1 focus:ring-blue-500"
                            />
                          </td>

                          {/* Joining Date */}
                          <td className="p-2">
                            <input
                              type="date"
                              value={row.joinDate || todayDateStr}
                              onChange={(e) => updateBulkRow(row.id, 'joinDate', e.target.value)}
                              className="w-full text-xs font-medium bg-white border border-slate-300 rounded px-1.5 py-1 focus:outline-none focus:ring-1 focus:ring-blue-500"
                            />
                          </td>

                          {/* Salary Structure */}
                          <td className="p-2">
                            <select
                              value={row.structureType}
                              onChange={(e) => updateBulkRow(row.id, 'structureType', e.target.value as SalaryStructureType)}
                              className="w-full text-xs bg-slate-50 border border-slate-300 rounded px-1.5 py-1 focus:bg-white focus:outline-none focus:ring-1 focus:ring-blue-500"
                            >
                              <option value="fixed">Fixed</option>
                              <option value="hourly">Hourly</option>
                              <option value="contract">Contract</option>
                              <option value="piece_rate">Piece-rate</option>
                            </select>
                          </td>

                          {/* Base Salary */}
                          <td className="p-2">
                            <input
                              type="number"
                              min="0"
                              step="any"
                              value={row.baseSalary === 0 ? '' : row.baseSalary}
                              onChange={(e) => {
                                const val = e.target.value === '' ? 0 : parseFloat(e.target.value);
                                updateBulkRow(row.id, 'baseSalary', isNaN(val) ? 0 : val);
                              }}
                              placeholder="15000"
                              className="w-full text-xs font-bold text-slate-800 bg-white border border-slate-300 rounded px-2 py-1 focus:outline-none focus:ring-1 focus:ring-blue-500"
                            />
                          </td>

                          {/* Payment Method */}
                          <td className="p-2">
                            <select
                              value={row.preferredPaymentMethod}
                              onChange={(e) => updateBulkRow(row.id, 'preferredPaymentMethod', e.target.value as PaymentMethod)}
                              className={`w-full text-xs font-medium rounded px-1.5 py-1 border focus:outline-none focus:ring-1 ${
                                row.preferredPaymentMethod === 'cash'
                                  ? 'bg-emerald-50 text-emerald-800 border-emerald-300'
                                  : row.preferredPaymentMethod === 'upi'
                                  ? 'bg-purple-50 text-purple-800 border-purple-300'
                                  : 'bg-slate-50 text-slate-800 border-slate-300'
                              }`}
                            >
                              <option value="bank_transfer">🏦 Bank</option>
                              <option value="cash">💵 Cash</option>
                              <option value="upi">📱 UPI</option>
                              <option value="cheque">📝 Cheque</option>
                            </select>
                          </td>

                          {/* Account / Note */}
                          <td className="p-2">
                            <input
                              type="text"
                              value={row.accountNumber}
                              onChange={(e) => updateBulkRow(row.id, 'accountNumber', e.target.value)}
                              placeholder={row.preferredPaymentMethod === 'cash' ? 'Cash Counter' : 'Account / UPI'}
                              className="w-full text-xs bg-slate-50 border border-slate-200 rounded px-2 py-1 focus:bg-white focus:outline-none focus:ring-1 focus:ring-blue-500"
                            />
                          </td>

                          {/* PF Account No */}
                          <td className="p-2">
                            <input
                              type="text"
                              value={row.pfAccountNumber || ''}
                              onChange={(e) => updateBulkRow(row.id, 'pfAccountNumber', e.target.value)}
                              placeholder="e.g. MH/BAN/..."
                              className="w-full text-xs bg-slate-50 border border-slate-200 rounded px-2 py-1 focus:bg-white focus:outline-none focus:ring-1 focus:ring-blue-500"
                            />
                          </td>

                          {/* Action Delete */}
                          <td className="p-2 text-center">
                            <button
                              type="button"
                              onClick={() => handleRemoveBulkRow(row.id)}
                              className="p-1 rounded text-slate-400 hover:text-rose-600 hover:bg-rose-50 transition cursor-pointer"
                              title="Delete Row"
                            >
                              <Trash2 className="w-3.5 h-3.5" />
                            </button>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Multi-Row Summary & Submit Bar */}
            <div className="pt-3 border-t border-slate-200 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
              <div className="text-xs text-slate-500 flex items-center space-x-2">
                <span className="font-semibold text-slate-700">
                  {validRowCount} of {bulkRows.length} rows ready to onboard.
                </span>
                <span className="text-[10px] text-slate-400">
                  (Empty rows are automatically ignored)
                </span>
              </div>

              <div className="flex items-center space-x-2">
                <button
                  type="button"
                  onClick={onClose}
                  className="px-4 py-2 rounded-lg border border-slate-300 text-slate-600 hover:bg-slate-50 font-semibold cursor-pointer"
                >
                  Cancel
                </button>

                <button
                  type="button"
                  onClick={handleBulkSubmit}
                  disabled={validRowCount === 0}
                  className="px-5 py-2 rounded-lg bg-blue-600 hover:bg-blue-700 disabled:bg-slate-300 text-white font-bold text-xs shadow-xs transition flex items-center space-x-1.5 cursor-pointer"
                >
                  <Users className="w-4 h-4" />
                  <span>
                    {validRowCount > 0 
                      ? `Add All ${validRowCount} ${validRowCount === 1 ? 'Employee' : 'Employees'} in 1 Step` 
                      : 'Add Multiple Employees'
                    }
                  </span>
                </button>
              </div>
            </div>

          </div>
        )}

      </div>
    </div>
  );
};
