import { CompanySettings, EmployeeProfile, AttendanceRecord } from '../types/payroll';

export const DEFAULT_COMPANY_SETTINGS: CompanySettings = {
  name: 'Apex Global Technologies Inc.',
  logoUrl: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=160&auto=format&fit=crop&q=80',
  address: 'Suite 400, 750 Tech Innovation Boulevard, Silicon Valley, CA 94025',
  taxId: 'US-EIN-94-2849102',
  email: 'payroll@apexglobal.tech',
  phone: '+1 (800) 555-0199',
  website: 'www.apexglobal.tech',
  currency: 'USD',
  currencySymbol: '$',
  payCycleDayCount: 30,
  otRateMultiplier: 1.5,
  holidayOtMultiplier: 2.0,
  lateDeductionThreshold: 3, // 3 lates = 0.5 day wage deduction
  pfPercentage: 12,
  pfCapLimit: 1800,
  esiPercentage: 0.75,
  esiWageThreshold: 3000,
  ptSlabAmount: 200,
  companySignatoryName: 'Eleanor Vance',
  companySignatoryTitle: 'Head of Global People Operations',
};

export const INITIAL_EMPLOYEES: EmployeeProfile[] = [
  {
    id: 'emp-001',
    empId: 'AGT-1001',
    name: 'Alexander Wright',
    email: 'alexander.wright@apexglobal.tech',
    department: 'Engineering',
    designation: 'Principal Staff Architect',
    joinDate: '2022-03-15',
    structureType: 'fixed',
    baseSalary: 12500,
    bankName: 'JPMorgan Chase Bank',
    accountNumber: '****-****-8492',
    routingOrIfsc: 'CHASUS33',
    panOrTaxNumber: 'SSN-XXX-XX-4819',
    pfAccountNumber: 'PF-AGT-2022-1001',
    uanNumber: 'UAN100938472910',
    preferredPaymentMethod: 'bank_transfer',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    gender: 'Male',
  },
  {
    id: 'emp-002',
    empId: 'AGT-1002',
    name: 'Sophia Chen',
    email: 'sophia.chen@apexglobal.tech',
    department: 'Engineering',
    designation: 'Senior Frontend Engineer',
    joinDate: '2023-06-01',
    structureType: 'fixed',
    baseSalary: 8200,
    bankName: 'Bank of America',
    accountNumber: '****-****-3319',
    routingOrIfsc: 'BOFAUS3N',
    panOrTaxNumber: 'SSN-XXX-XX-9120',
    pfAccountNumber: 'PF-AGT-2023-1002',
    uanNumber: 'UAN100938472911',
    preferredPaymentMethod: 'bank_transfer',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
    gender: 'Female',
  },
  {
    id: 'emp-003',
    empId: 'AGT-1003',
    name: 'Marcus Holloway',
    email: 'marcus.holloway@apexglobal.tech',
    department: 'Product & Design',
    designation: 'Lead Product Designer',
    joinDate: '2024-01-10',
    structureType: 'fixed',
    baseSalary: 7500,
    bankName: 'Wells Fargo Bank',
    accountNumber: '****-****-5521',
    routingOrIfsc: 'WFBIUS6S',
    panOrTaxNumber: 'SSN-XXX-XX-3012',
    pfAccountNumber: 'PF-AGT-2024-1003',
    uanNumber: 'UAN100938472912',
    preferredPaymentMethod: 'cash',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    gender: 'Male',
  },
  {
    id: 'emp-004',
    empId: 'AGT-1004',
    name: 'Amara Patel',
    email: 'amara.patel@apexglobal.tech',
    department: 'Sales & Marketing',
    designation: 'Enterprise Account Executive',
    joinDate: '2023-11-20',
    structureType: 'fixed',
    baseSalary: 6800,
    bankName: 'Citibank N.A.',
    accountNumber: '****-****-7740',
    routingOrIfsc: 'CITIUS33',
    panOrTaxNumber: 'SSN-XXX-XX-6531',
    pfAccountNumber: 'PF-AGT-2023-1004',
    uanNumber: 'UAN100938472913',
    preferredPaymentMethod: 'upi',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80',
    gender: 'Female',
  },
  {
    id: 'emp-005',
    empId: 'AGT-1005',
    name: 'David Rodriguez',
    email: 'david.rodriguez@apexglobal.tech',
    department: 'Operations & Support',
    designation: 'Cloud DevOps Specialist (Hourly)',
    joinDate: '2024-05-15',
    structureType: 'hourly',
    baseSalary: 38, // Hourly rate
    hourlyRate: 38,
    bankName: 'Silicon Valley Bank / First Citizens',
    accountNumber: '****-****-9102',
    routingOrIfsc: 'SVBKUS6S',
    panOrTaxNumber: 'SSN-XXX-XX-7821',
    pfAccountNumber: 'PF-AGT-2024-1005',
    uanNumber: 'UAN100938472914',
    preferredPaymentMethod: 'cash',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    gender: 'Male',
  },
  {
    id: 'emp-006',
    empId: 'AGT-1006',
    name: 'Elena Rostova',
    email: 'elena.rostova@apexglobal.tech',
    department: 'Finance & Legal',
    designation: 'Senior Financial Controller',
    joinDate: '2021-08-01',
    structureType: 'fixed',
    baseSalary: 9400,
    bankName: 'PNC Bank',
    accountNumber: '****-****-1144',
    routingOrIfsc: 'PNCCUS33',
    panOrTaxNumber: 'SSN-XXX-XX-1198',
    pfAccountNumber: 'PF-AGT-2021-1006',
    uanNumber: 'UAN100938472915',
    preferredPaymentMethod: 'bank_transfer',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
    gender: 'Female',
  },
  {
    id: 'emp-007',
    empId: 'AGT-1007',
    name: 'Liam Gallagher',
    email: 'liam.gallagher@apexglobal.tech',
    department: 'Engineering',
    designation: 'Associate QA Automation Engineer (Probation)',
    joinDate: '2026-08-10', // Mid-month joiner!
    isProbation: true,
    structureType: 'fixed',
    baseSalary: 4500,
    bankName: 'Capital One Bank',
    accountNumber: '****-****-6632',
    routingOrIfsc: 'CAPITUS3',
    panOrTaxNumber: 'SSN-XXX-XX-4421',
    pfAccountNumber: 'PF-AGT-2026-1007',
    uanNumber: 'UAN100938472916',
    preferredPaymentMethod: 'cash',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80',
    gender: 'Male',
  },
  {
    id: 'emp-008',
    empId: 'AGT-1008',
    name: 'Kavita Sharma',
    email: 'kavita.sharma@apexglobal.tech',
    department: 'Human Resources',
    designation: 'HR Business Partner & Talent Lead',
    joinDate: '2023-03-01',
    structureType: 'fixed',
    baseSalary: 6200,
    bankName: 'JPMorgan Chase Bank',
    accountNumber: '****-****-9923',
    routingOrIfsc: 'CHASUS33',
    panOrTaxNumber: 'SSN-XXX-XX-8840',
    pfAccountNumber: 'PF-AGT-2023-1008',
    uanNumber: 'UAN100938472917',
    preferredPaymentMethod: 'bank_transfer',
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=100&auto=format&fit=crop&q=80',
    gender: 'Female',
  }
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    empId: 'AGT-1001',
    employeeName: 'Alexander Wright',
    department: 'Engineering',
    totalMonthDays: 30,
    daysPresent: 28,
    daysAbsent: 0,
    halfDays: 0,
    paidLeaves: 2,
    unpaidLeaves: 0,
    overtimeHours: 14,
    holidayOvertimeHours: 6,
    lateArrivalsCount: 0,
    earlyDeparturesCount: 0,
    holidaysWorked: 1,
    remarks: 'Consistent delivery on Q3 Architecture sprint',
  },
  {
    empId: 'AGT-1002',
    employeeName: 'Sophia Chen',
    department: 'Engineering',
    totalMonthDays: 30,
    daysPresent: 26,
    daysAbsent: 1,
    halfDays: 2,
    paidLeaves: 1,
    unpaidLeaves: 1, // 1 day LOP
    overtimeHours: 18.5,
    holidayOvertimeHours: 0,
    lateArrivalsCount: 4, // triggers late penalty
    earlyDeparturesCount: 1,
    holidaysWorked: 0,
    remarks: 'Critical release deployment support',
  },
  {
    empId: 'AGT-1003',
    employeeName: 'Marcus Holloway',
    department: 'Product & Design',
    totalMonthDays: 30,
    daysPresent: 29,
    daysAbsent: 0,
    halfDays: 0,
    paidLeaves: 1,
    unpaidLeaves: 0,
    overtimeHours: 5,
    holidayOvertimeHours: 0,
    lateArrivalsCount: 1,
    earlyDeparturesCount: 0,
    holidaysWorked: 0,
    remarks: 'Design system overhaul on schedule',
  },
  {
    empId: 'AGT-1004',
    employeeName: 'Amara Patel',
    department: 'Sales & Marketing',
    totalMonthDays: 30,
    daysPresent: 27,
    daysAbsent: 0,
    halfDays: 0,
    paidLeaves: 3,
    unpaidLeaves: 0,
    overtimeHours: 8,
    holidayOvertimeHours: 0,
    lateArrivalsCount: 2,
    earlyDeparturesCount: 0,
    holidaysWorked: 0,
    remarks: 'Closed Tier-1 Enterprise deal in August',
  },
  {
    empId: 'AGT-1005',
    employeeName: 'David Rodriguez',
    department: 'Operations & Support',
    totalMonthDays: 30,
    daysPresent: 22,
    daysAbsent: 0,
    halfDays: 0,
    paidLeaves: 0,
    unpaidLeaves: 0,
    overtimeHours: 32, // High overtime for infrastructure migration
    holidayOvertimeHours: 8,
    lateArrivalsCount: 0,
    earlyDeparturesCount: 0,
    holidaysWorked: 2,
    remarks: 'Weekend Cloud Migration maintenance shift',
  },
  {
    empId: 'AGT-1006',
    employeeName: 'Elena Rostova',
    department: 'Finance & Legal',
    totalMonthDays: 30,
    daysPresent: 30,
    daysAbsent: 0,
    halfDays: 0,
    paidLeaves: 0,
    unpaidLeaves: 0,
    overtimeHours: 10,
    holidayOvertimeHours: 4,
    lateArrivalsCount: 0,
    earlyDeparturesCount: 0,
    holidaysWorked: 1,
    remarks: 'Mid-year audit compliance preparation',
  },
  {
    empId: 'AGT-1007',
    employeeName: 'Liam Gallagher',
    department: 'Engineering',
    totalMonthDays: 30,
    daysPresent: 16, // Joined mid-month on Aug 10th (21 active days in period)
    daysAbsent: 0,
    halfDays: 0,
    paidLeaves: 0,
    unpaidLeaves: 0,
    overtimeHours: 0,
    holidayOvertimeHours: 0,
    lateArrivalsCount: 0,
    earlyDeparturesCount: 0,
    holidaysWorked: 0,
    remarks: 'Joined on Aug 10, 2026. Prorated active days.',
  },
  {
    empId: 'AGT-1008',
    employeeName: 'Kavita Sharma',
    department: 'Human Resources',
    totalMonthDays: 30,
    daysPresent: 28,
    daysAbsent: 0,
    halfDays: 0,
    paidLeaves: 2,
    unpaidLeaves: 0,
    overtimeHours: 6,
    holidayOvertimeHours: 0,
    lateArrivalsCount: 1,
    earlyDeparturesCount: 0,
    holidaysWorked: 0,
    remarks: 'Managed quarterly performance reviews',
  }
];
