import { CompanySettings, EmployeeProfile, AttendanceRecord, SalaryBreakdown } from '../types/payroll';

export const DEFAULT_COMPANY_SETTINGS: CompanySettings = {
  name: 'iMatrix Technology Solutions',
  appTitle: 'iMatrix Technology Solutions',
  brandSubTitle: 'Payroll Management System',
  logoUrl: '/imatrix-logo.svg',
  address: 'Tech Innovation Hub, Cyber Towers, Level 4, Chennai, TN',
  taxId: 'GSTIN33AAACI9821F1Z8',
  email: 'payroll@imatrix.tech',
  phone: '+91 98400 12345',
  website: 'www.imatrix.tech',
  currency: 'INR',
  currencySymbol: '₹',
  payCycleDayCount: 30,
  otRateMultiplier: 1.5,
  holidayOtMultiplier: 2.0,
  lateDeductionThreshold: 3, // 3 lates = 0.5 day wage deduction
  pfPercentage: 0,
  pfCapLimit: 1800,
  enablePF: false,
  esiPercentage: 0.75,
  esiWageThreshold: 21000,
  ptSlabAmount: 0,
  enablePT: false,
  companySignatoryName: 'Authorized Signatory',
  companySignatoryTitle: 'Head of Operations & Finance',
  showDigitalSignature: true,
  signatureTimestamp: true,
  signatureType: 'preset',
};

export const INITIAL_EMPLOYEES: EmployeeProfile[] = [
  {
    id: 'emp-001',
    empId: 'AGT-1001',
    name: 'Alexander Wright',
    email: 'alexander.wright@imatrix.tech',
    department: 'XML',
    designation: 'Principal XML Specialist',
    joinDate: '2022-03-15',
    structureType: 'fixed',
    baseSalary: 12500,
    bankName: 'JPMorgan Chase Bank',
    accountNumber: '****-****-8492',
    routingOrIfsc: 'CHASUS33',
    panOrTaxNumber: 'SSN-XXX-XX-4819',
    pfAccountNumber: 'PF-AGT-2022-1001',
    uanNumber: 'UAN100938472910',
    preferredPaymentMethod: 'bank_transfer',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    gender: 'Male',
  },
  {
    id: 'emp-002',
    empId: 'AGT-1002',
    name: 'Sophia Chen',
    email: 'sophia.chen@imatrix.tech',
    department: 'ePub',
    designation: 'Senior ePub Lead',
    joinDate: '2023-06-01',
    structureType: 'fixed',
    baseSalary: 8200,
    bankName: 'Bank of America',
    accountNumber: '****-****-3319',
    routingOrIfsc: 'BOFAUS3N',
    panOrTaxNumber: 'SSN-XXX-XX-9120',
    pfAccountNumber: 'PF-AGT-2023-1002',
    uanNumber: 'UAN100938472911',
    preferredPaymentMethod: 'bank_transfer',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
    gender: 'Female',
  },
  {
    id: 'emp-003',
    empId: 'AGT-1003',
    name: 'Marcus Holloway',
    email: 'marcus.holloway@imatrix.tech',
    department: 'PPT',
    designation: 'Lead PPT Designer',
    joinDate: '2024-01-10',
    structureType: 'fixed',
    baseSalary: 7500,
    bankName: 'Wells Fargo Bank',
    accountNumber: '****-****-5521',
    routingOrIfsc: 'WFBIUS6S',
    panOrTaxNumber: 'SSN-XXX-XX-3012',
    pfAccountNumber: 'PF-AGT-2024-1003',
    uanNumber: 'UAN100938472912',
    preferredPaymentMethod: 'cash',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    gender: 'Male',
  },
  {
    id: 'emp-004',
    empId: 'AGT-1004',
    name: 'Amara Patel',
    email: 'amara.patel@imatrix.tech',
    department: 'Word',
    designation: 'Word Processing Lead',
    joinDate: '2023-11-20',
    structureType: 'fixed',
    baseSalary: 6800,
    bankName: 'Citibank N.A.',
    accountNumber: '****-****-7740',
    routingOrIfsc: 'CITIUS33',
    panOrTaxNumber: 'SSN-XXX-XX-6531',
    pfAccountNumber: 'PF-AGT-2023-1004',
    uanNumber: 'UAN100938472913',
    preferredPaymentMethod: 'upi',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80',
    gender: 'Female',
  },
  {
    id: 'emp-005',
    empId: 'AGT-1005',
    name: 'David Rodriguez',
    email: 'david.rodriguez@imatrix.tech',
    department: 'XML',
    designation: 'XML DTD & Schema Specialist',
    joinDate: '2024-05-15',
    structureType: 'hourly',
    baseSalary: 38, // Hourly rate
    hourlyRate: 38,
    bankName: 'Silicon Valley Bank / First Citizens',
    accountNumber: '****-****-9102',
    routingOrIfsc: 'SVBKUS6S',
    panOrTaxNumber: 'SSN-XXX-XX-7821',
    pfAccountNumber: 'PF-AGT-2024-1005',
    uanNumber: 'UAN100938472914',
    preferredPaymentMethod: 'cash',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    gender: 'Male',
  },
  {
    id: 'emp-006',
    empId: 'AGT-1006',
    name: 'Elena Rostova',
    email: 'elena.rostova@imatrix.tech',
    department: 'ePub',
    designation: 'Digital Publishing Specialist',
    joinDate: '2021-08-01',
    structureType: 'fixed',
    baseSalary: 9400,
    bankName: 'PNC Bank',
    accountNumber: '****-****-1144',
    routingOrIfsc: 'PNCCUS33',
    panOrTaxNumber: 'SSN-XXX-XX-1198',
    pfAccountNumber: 'PF-AGT-2021-1006',
    uanNumber: 'UAN100938472915',
    preferredPaymentMethod: 'bank_transfer',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
    gender: 'Female',
  },
  {
    id: 'emp-007',
    empId: 'AGT-1007',
    name: 'Liam Gallagher',
    email: 'liam.gallagher@imatrix.tech',
    department: 'PPT',
    designation: 'PPT Formatting Associate',
    joinDate: '2026-08-10', // Mid-month joiner!
    isProbation: true,
    structureType: 'fixed',
    baseSalary: 4500,
    bankName: 'Capital One Bank',
    accountNumber: '****-****-6632',
    routingOrIfsc: 'CAPITUS3',
    panOrTaxNumber: 'SSN-XXX-XX-4421',
    pfAccountNumber: 'PF-AGT-2026-1007',
    uanNumber: 'UAN100938472916',
    preferredPaymentMethod: 'cash',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=80',
    gender: 'Male',
  },
  {
    id: 'emp-008',
    empId: 'AGT-1008',
    name: 'Kavita Sharma',
    email: 'kavita.sharma@imatrix.tech',
    department: 'Word',
    designation: 'Senior Word Styler',
    joinDate: '2023-03-01',
    structureType: 'fixed',
    baseSalary: 6200,
    bankName: 'JPMorgan Chase Bank',
    accountNumber: '****-****-9923',
    routingOrIfsc: 'CHASUS33',
    panOrTaxNumber: 'SSN-XXX-XX-8840',
    pfAccountNumber: 'PF-AGT-2023-1008',
    uanNumber: 'UAN100938472917',
    preferredPaymentMethod: 'bank_transfer',
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=100&auto=format&fit=crop&q=80',
    gender: 'Female',
  }
];

export const INITIAL_HISTORICAL_PAYSLIPS: SalaryBreakdown[] = [
  // Alexander Wright - July 2026
  {
    id: 'hist-agt1001-2026-07',
    empId: 'AGT-1001',
    month: '2026-07',
    periodLabel: 'July 2026',
    profile: INITIAL_EMPLOYEES[0],
    attendance: {
      empId: 'AGT-1001',
      employeeName: 'Alexander Wright',
      department: 'XML',
      totalMonthDays: 31,
      daysPresent: 30,
      daysAbsent: 0,
      halfDays: 0,
      paidLeaves: 1,
      unpaidLeaves: 0,
      overtimeHours: 10,
      holidayOvertimeHours: 0,
      lateArrivalsCount: 0,
      earlyDeparturesCount: 0,
      holidaysWorked: 0,
      remarks: 'July XML schema delivery',
    },
    totalDays: 30,
    payableDays: 30,
    lossOfPayDays: 0,
    basicPay: 6250,
    hra: 2500,
    dearnessAllowance: 625,
    conveyanceAllowance: 800,
    medicalAllowance: 600,
    specialAllowance: 1725,
    overtimePay: 937.5,
    holidayWorkPay: 0,
    performanceBonus: 500,
    reimbursements: 0,
    grossEarnings: 13937.5,
    providentFund: 750,
    employerPF: 750,
    esi: 0,
    professionalTax: 200,
    incomeTaxTDS: 1100,
    lossOfPayDeduction: 0,
    lateDeduction: 0,
    loanAdvance: 0,
    otherDeductions: 0,
    totalDeductions: 2050,
    netPay: 11887.5,
    netPayInWords: 'Eleven Thousand Eight Hundred Eighty-Seven and 50/100',
    paymentMethod: 'bank_transfer',
    paymentReference: 'ACH-202607-AGT1001',
    paymentStatus: 'paid',
    paidAt: '2026-07-31T17:00:00.000Z',
    status: 'approved',
    isCustomAdjusted: false,
    lastUpdated: '2026-07-31T17:00:00.000Z',
  },
  // Alexander Wright - June 2026
  {
    id: 'hist-agt1001-2026-06',
    empId: 'AGT-1001',
    month: '2026-06',
    periodLabel: 'June 2026',
    profile: INITIAL_EMPLOYEES[0],
    attendance: {
      empId: 'AGT-1001',
      employeeName: 'Alexander Wright',
      department: 'XML',
      totalMonthDays: 30,
      daysPresent: 28,
      daysAbsent: 0,
      halfDays: 0,
      paidLeaves: 2,
      unpaidLeaves: 0,
      overtimeHours: 6,
      holidayOvertimeHours: 0,
      lateArrivalsCount: 0,
      earlyDeparturesCount: 0,
      holidaysWorked: 0,
    },
    totalDays: 30,
    payableDays: 30,
    lossOfPayDays: 0,
    basicPay: 6250,
    hra: 2500,
    dearnessAllowance: 625,
    conveyanceAllowance: 800,
    medicalAllowance: 600,
    specialAllowance: 1725,
    overtimePay: 562.5,
    holidayWorkPay: 0,
    performanceBonus: 0,
    reimbursements: 0,
    grossEarnings: 13062.5,
    providentFund: 750,
    employerPF: 750,
    esi: 0,
    professionalTax: 200,
    incomeTaxTDS: 1050,
    lossOfPayDeduction: 0,
    lateDeduction: 0,
    loanAdvance: 0,
    otherDeductions: 0,
    totalDeductions: 2000,
    netPay: 11062.5,
    netPayInWords: 'Eleven Thousand Sixty-Two and 50/100',
    paymentMethod: 'bank_transfer',
    paymentReference: 'ACH-202606-AGT1001',
    paymentStatus: 'paid',
    paidAt: '2026-06-30T17:00:00.000Z',
    status: 'approved',
    isCustomAdjusted: false,
    lastUpdated: '2026-06-30T17:00:00.000Z',
  },
  // Sophia Chen - July 2026
  {
    id: 'hist-agt1002-2026-07',
    empId: 'AGT-1002',
    month: '2026-07',
    periodLabel: 'July 2026',
    profile: INITIAL_EMPLOYEES[1],
    attendance: {
      empId: 'AGT-1002',
      employeeName: 'Sophia Chen',
      department: 'ePub',
      totalMonthDays: 31,
      daysPresent: 29,
      daysAbsent: 0,
      halfDays: 0,
      paidLeaves: 2,
      unpaidLeaves: 0,
      overtimeHours: 8,
      holidayOvertimeHours: 0,
      lateArrivalsCount: 0,
      earlyDeparturesCount: 0,
      holidaysWorked: 0,
    },
    totalDays: 30,
    payableDays: 30,
    lossOfPayDays: 0,
    basicPay: 4100,
    hra: 1640,
    dearnessAllowance: 410,
    conveyanceAllowance: 800,
    medicalAllowance: 600,
    specialAllowance: 650,
    overtimePay: 492,
    holidayWorkPay: 0,
    performanceBonus: 300,
    reimbursements: 0,
    grossEarnings: 8992,
    providentFund: 492,
    employerPF: 492,
    esi: 0,
    professionalTax: 200,
    incomeTaxTDS: 620,
    lossOfPayDeduction: 0,
    lateDeduction: 0,
    loanAdvance: 0,
    otherDeductions: 0,
    totalDeductions: 1312,
    netPay: 7680,
    netPayInWords: 'Seven Thousand Six Hundred Eighty',
    paymentMethod: 'bank_transfer',
    paymentReference: 'ACH-202607-AGT1002',
    paymentStatus: 'paid',
    paidAt: '2026-07-31T17:00:00.000Z',
    status: 'approved',
    isCustomAdjusted: false,
    lastUpdated: '2026-07-31T17:00:00.000Z',
  },
  // Elena Rostova - May 2026
  {
    id: 'hist-agt1006-2026-05',
    empId: 'AGT-1006',
    month: '2026-05',
    periodLabel: 'May 2026',
    profile: INITIAL_EMPLOYEES[5],
    attendance: {
      empId: 'AGT-1006',
      employeeName: 'Elena Rostova',
      department: 'ePub',
      totalMonthDays: 31,
      daysPresent: 30,
      daysAbsent: 0,
      halfDays: 0,
      paidLeaves: 1,
      unpaidLeaves: 0,
      overtimeHours: 12,
      holidayOvertimeHours: 0,
      lateArrivalsCount: 0,
      earlyDeparturesCount: 0,
      holidaysWorked: 0,
    },
    totalDays: 30,
    payableDays: 30,
    lossOfPayDays: 0,
    basicPay: 4700,
    hra: 1880,
    dearnessAllowance: 470,
    conveyanceAllowance: 800,
    medicalAllowance: 600,
    specialAllowance: 950,
    overtimePay: 846,
    holidayWorkPay: 0,
    performanceBonus: 400,
    reimbursements: 0,
    grossEarnings: 10646,
    providentFund: 564,
    employerPF: 564,
    esi: 0,
    professionalTax: 200,
    incomeTaxTDS: 850,
    lossOfPayDeduction: 0,
    lateDeduction: 0,
    loanAdvance: 0,
    otherDeductions: 0,
    totalDeductions: 1614,
    netPay: 9032,
    netPayInWords: 'Nine Thousand Thirty-Two',
    paymentMethod: 'bank_transfer',
    paymentReference: 'ACH-202605-AGT1006',
    paymentStatus: 'paid',
    paidAt: '2026-05-31T17:00:00.000Z',
    status: 'approved',
    isCustomAdjusted: false,
    lastUpdated: '2026-05-31T17:00:00.000Z',
  }
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    empId: 'AGT-1001',
    employeeName: 'Alexander Wright',
    department: 'XML',
    totalMonthDays: 30,
    daysPresent: 28,
    daysAbsent: 0,
    halfDays: 0,
    paidLeaves: 2,
    unpaidLeaves: 0,
    overtimeHours: 8,
    holidayOvertimeHours: 0,
    lateArrivalsCount: 1,
    earlyDeparturesCount: 0,
    holidaysWorked: 0,
  },
  {
    empId: 'AGT-1002',
    employeeName: 'Sophia Chen',
    department: 'Software Development',
    totalMonthDays: 30,
    daysPresent: 29,
    daysAbsent: 0,
    halfDays: 0,
    paidLeaves: 1,
    unpaidLeaves: 0,
    overtimeHours: 12,
    holidayOvertimeHours: 4,
    lateArrivalsCount: 0,
    earlyDeparturesCount: 0,
    holidaysWorked: 1,
  },
  {
    empId: 'AGT-1003',
    employeeName: 'Marcus Vance',
    department: 'Digital Marketing',
    totalMonthDays: 30,
    daysPresent: 27,
    daysAbsent: 1,
    halfDays: 1,
    paidLeaves: 1,
    unpaidLeaves: 1,
    overtimeHours: 4,
    holidayOvertimeHours: 0,
    lateArrivalsCount: 2,
    earlyDeparturesCount: 0,
    holidaysWorked: 0,
  },
  {
    empId: 'AGT-1004',
    employeeName: 'Priya Sharma',
    department: 'Finance & Accounts',
    totalMonthDays: 30,
    daysPresent: 30,
    daysAbsent: 0,
    halfDays: 0,
    paidLeaves: 0,
    unpaidLeaves: 0,
    overtimeHours: 10,
    holidayOvertimeHours: 0,
    lateArrivalsCount: 0,
    earlyDeparturesCount: 0,
    holidaysWorked: 0,
  },
  {
    empId: 'AGT-1005',
    employeeName: 'David Rodriguez',
    department: 'Software Development',
    totalMonthDays: 30,
    daysPresent: 28,
    daysAbsent: 0,
    halfDays: 0,
    paidLeaves: 2,
    unpaidLeaves: 0,
    overtimeHours: 16,
    holidayOvertimeHours: 6,
    lateArrivalsCount: 1,
    earlyDeparturesCount: 0,
    holidaysWorked: 1,
  },
  {
    empId: 'AGT-1006',
    employeeName: 'Emily Watson',
    department: 'Human Resources',
    totalMonthDays: 30,
    daysPresent: 30,
    daysAbsent: 0,
    halfDays: 0,
    paidLeaves: 0,
    unpaidLeaves: 0,
    overtimeHours: 0,
    holidayOvertimeHours: 0,
    lateArrivalsCount: 0,
    earlyDeparturesCount: 0,
    holidaysWorked: 0,
  },
  {
    empId: 'AGT-1007',
    employeeName: 'James Wilson',
    department: 'Operations',
    totalMonthDays: 30,
    daysPresent: 26,
    daysAbsent: 2,
    halfDays: 0,
    paidLeaves: 2,
    unpaidLeaves: 2,
    overtimeHours: 6,
    holidayOvertimeHours: 0,
    lateArrivalsCount: 3,
    earlyDeparturesCount: 1,
    holidaysWorked: 0,
  },
  {
    empId: 'AGT-1008',
    employeeName: 'Aisha Patel',
    department: 'Quality Assurance',
    totalMonthDays: 30,
    daysPresent: 29,
    daysAbsent: 0,
    halfDays: 0,
    paidLeaves: 1,
    unpaidLeaves: 0,
    overtimeHours: 5,
    holidayOvertimeHours: 0,
    lateArrivalsCount: 0,
    earlyDeparturesCount: 0,
    holidaysWorked: 0,
  }
];
